spring:
  aplication:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: verificaCred
      password: comi1bolo

server:
  port: 8762

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false